import { Metadata } from 'next';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';
import HolidaySalesDetail from '@/components/sections/HolidaySalesDetail';
import { getHolidayCoupons } from '@/lib/api';
import { getHolidayBannerPlaceholder } from '@/lib/placeholders';

interface Props {
  params: Promise<{ 'holiday-slug': string }>;
}

// 节日名称映射 - 支持URL slug到节日名称的转换
const holidaySlugMap: { [key: string]: string } = {
  // 季节促销
  'summer-sale': 'Summer Sale',
  'winter-sale': 'Winter Sale', 
  'spring-sale': 'Spring Sale',
  'fall-sale': 'Fall Sale',
  'autumn-sale': 'Autumn Sale',
  
  // 主要购物节
  'black-friday': 'Black Friday',
  'cyber-monday': 'Cyber Monday',
  'prime-day': 'Prime Day',
  'boxing-day': 'Boxing Day',
  
  // 联邦节日
  'new-years-day': "New Year's Day",
  'martin-luther-king-jr-day': 'Martin Luther King Jr. Day',
  'presidents-day': "Presidents' Day", 
  'memorial-day': 'Memorial Day',
  'independence-day': 'Independence Day',
  'labor-day': 'Labor Day',
  'columbus-day': 'Columbus Day',
  'veterans-day': 'Veterans Day',
  'thanksgiving-day': 'Thanksgiving Day',
  'christmas-day': 'Christmas Day',
  
  // 文化节日
  'valentines-day': "Valentine's Day",
  'st-patricks-day': "St. Patrick's Day", 
  'easter-sunday': 'Easter Sunday',
  'mothers-day': "Mother's Day",
  'fathers-day': "Father's Day",
  'halloween': 'Halloween',
  
  // 特殊活动
  'back-to-school': 'Back to School',
  'end-of-year': 'End of Year',
  'womens-equality-day': "Women's Equality Day",
  'earth-day': 'Earth Day',
  'april-fools-day': "April Fool's Day",
  'groundhog-day': 'Groundhog Day',
  'mardi-gras': 'Mardi Gras',
  'cinco-de-mayo': 'Cinco de Mayo',
  'flag-day': 'Flag Day',
  'national-donut-day': 'National Donut Day',
  'world-health-day': 'World Health Day',
  'international-womens-day': "International Women's Day",
  
  // 宗教节日
  'good-friday': 'Good Friday',
  'palm-sunday': 'Palm Sunday',
  'ash-wednesday': 'Ash Wednesday',
  'passover': 'Passover',
  'rosh-hashanah': 'Rosh Hashanah',
  'yom-kippur': 'Yom Kippur',
  'hanukkah': 'Hanukkah',
  'kwanzaa': 'Kwanzaa',
  
  // 月度促销
  'january-sale': 'January Sale',
  'february-sale': 'February Sale',
  'march-sale': 'March Sale',
  'april-sale': 'April Sale', 
  'may-sale': 'May Sale',
  'june-sale': 'June Sale',
  'july-sale': 'July Sale',
  'august-sale': 'August Sale',
  'september-sale': 'September Sale',
  'october-sale': 'October Sale',
  'november-sale': 'November Sale',
  'december-sale': 'December Sale'
};

// Holiday images mapping - generated by generate-holiday-images.js script
const holidayImages: { [key: string]: string } = {
  // Will be populated by the script, example:
  //  'black-friday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/black-friday-sale-banner.webp',
  //  'cyber-monday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/cyber-monday-sale-banner.webp',
  // Add more as images are generated...  'summer-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/summer-sale-sale-banner.webp',  'winter-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/winter-sale-sale-banner.webp',  'spring-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/spring-sale-sale-banner.webp',  'fall-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/fall-sale-sale-banner.webp',  'autumn-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/autumn-sale-sale-banner.webp',  'prime-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/prime-day-sale-banner.webp',  'boxing-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/boxing-day-sale-banner.webp',  'new-years-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/new-years-day-sale-banner.webp',  'martin-luther-king-jr-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/martin-luther-king-jr-day-sale-banner.webp',  'presidents-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/presidents-day-sale-banner.webp',  'memorial-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/memorial-day-sale-banner.webp',  'independence-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/independence-day-sale-banner.webp',  'labor-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/labor-day-sale-banner.webp',  'columbus-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/columbus-day-sale-banner.webp',  'veterans-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/veterans-day-sale-banner.webp',  'thanksgiving-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/thanksgiving-day-sale-banner.webp',  'christmas-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/christmas-day-sale-banner.webp',  'valentines-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/valentines-day-sale-banner.webp',  'st-patricks-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/st-patricks-day-sale-banner.webp',  'easter-sunday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/easter-sunday-sale-banner.webp',  'mothers-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/mothers-day-sale-banner.webp',  'fathers-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/fathers-day-sale-banner.webp',  'halloween': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/halloween-sale-banner.webp',  'back-to-school': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/back-to-school-sale-banner.webp',  'end-of-year': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/end-of-year-sale-banner.webp',  'womens-equality-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/womens-equality-day-sale-banner.webp',  'earth-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/earth-day-sale-banner.webp',  'april-fools-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/april-fools-day-sale-banner.webp',  'groundhog-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/groundhog-day-sale-banner.webp',  'mardi-gras': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/mardi-gras-sale-banner.webp',  'cinco-de-mayo': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/cinco-de-mayo-sale-banner.webp',  'flag-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/flag-day-sale-banner.webp',  'national-donut-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/national-donut-day-sale-banner.webp',  'world-health-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/world-health-day-sale-banner.webp',  'international-womens-day': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/international-womens-day-sale-banner.webp',  'good-friday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/good-friday-sale-banner.webp',  'palm-sunday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/palm-sunday-sale-banner.webp',  'ash-wednesday': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/ash-wednesday-sale-banner.webp',  'passover': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/passover-sale-banner.webp',  'rosh-hashanah': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/rosh-hashanah-sale-banner.webp',  'yom-kippur': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/yom-kippur-sale-banner.webp',  'hanukkah': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/hanukkah-sale-banner.webp',  'kwanzaa': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/kwanzaa-sale-banner.webp',  'january-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/january-sale-sale-banner.webp',  'february-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/february-sale-sale-banner.webp',  'march-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/march-sale-sale-banner.webp',  'april-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/april-sale-sale-banner.webp',  'may-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/may-sale-sale-banner.webp',  'june-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/june-sale-sale-banner.webp',  'july-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/july-sale-sale-banner.webp',  'august-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/august-sale-sale-banner.webp',  'september-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/september-sale-sale-banner.webp',  'october-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/october-sale-sale-banner.webp',  'november-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/november-sale-sale-banner.webp',  'december-sale': 'https://pub-d4a6e4bb69c749d08347ce9216e8201a.r2.dev/holiday-images/december-sale-sale-banner.webp',
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { 'holiday-slug': holidaySlug } = await params;
  const holidayName = holidaySlugMap[holidaySlug] || holidaySlug.replace(/-/g, ' ');
  
  return {
    title: `${holidayName} Deals & Coupons - Save Big | CouponMia`,
    description: `Discover exclusive ${holidayName} deals and discount codes. Save money with verified coupons from top retailers during ${holidayName} sales.`,
    alternates: {
      canonical: `https://couponmia.com/holidays/${holidaySlug}`
    }
  };
}

export default async function HolidaySalePage({ params }: Props) {
  const { 'holiday-slug': holidaySlug } = await params;
  const holidayName = holidaySlugMap[holidaySlug] || holidaySlug.replace(/-/g, ' ');
  const holidayImage = holidayImages[holidaySlug];
  
  // 获取该节日的促销数据
  const holidayData = await getHolidayCoupons(holidayName, 50);

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-brand-lightest">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* 页面标题 */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-text-primary mb-4">
            {holidayName} Deals & Coupons
          </h1>
          <p className="text-text-secondary text-xl max-w-3xl mx-auto">
            Discover exclusive discounts and promotional offers for {holidayName}. 
            Save money with verified coupons from your favorite stores.
          </p>
        </div>

        {/* Holiday Image */}
        <div className="mb-12 rounded-2xl overflow-hidden shadow-2xl">
          <img 
            src={holidayImage || getHolidayBannerPlaceholder()} 
            alt={`${holidayName} Sale Banner`}
            className="w-full h-32 md:h-40 lg:h-48 object-cover"
            loading="eager"
          />
        </div>

        {/* 统计信息 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <div className="bg-card-bg/90 backdrop-blur-sm rounded-2xl p-6 text-center border border-card-border">
            <div className="text-3xl font-bold text-brand-light mb-2">
              {holidayData.length}
            </div>
            <div className="text-text-secondary">Available Deals</div>
          </div>
          <div className="bg-card-bg/90 backdrop-blur-sm rounded-2xl p-6 text-center border border-card-border">
            <div className="text-3xl font-bold text-green-500 mb-2">
              {new Set(holidayData.map(item => item.coupon?.store?.name).filter(Boolean)).size}
            </div>
            <div className="text-text-secondary">Featured Stores</div>
          </div>
          <div className="bg-card-bg/90 backdrop-blur-sm rounded-2xl p-6 text-center border border-card-border">
            <div className="text-3xl font-bold text-purple-500 mb-2">
              {holidayData.filter(item => item.coupon?.code).length}
            </div>
            <div className="text-text-secondary">Coupon Codes</div>
          </div>
        </div>

        {/* 节日促销详情 */}
        <HolidaySalesDetail 
          holidayName={holidayName}
          holidayData={holidayData}
        />
      </main>
      
      <Footer />
    </div>
  );
}

// 静态生成常见节日路径
export async function generateStaticParams() {
  const commonHolidays = [
    'summer-sale',
    'winter-sale',
    'black-friday', 
    'cyber-monday',
    'christmas-day',
    'halloween',
    'valentines-day',
    'mothers-day',
    'fathers-day'
  ];
  
  return commonHolidays.map((slug) => ({
    'holiday-slug': slug,
  }));
}